[features]
seeds = false
skip-lint = false
[programs.devnet]
migration_program = "GaK9khMjEUcFszCnL2AsueRgdT2JYU1yK3tj9RHETpi4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/chou/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/migration-program.ts"
